### ISSUE TITLE
Pourquoi se baser sur bitcoin ?

### ISSUE THREAD

**Issue by Jorropo** [Chaine-de-Blocs/educoin#3]
Je trouve le projet hyper intéréssant mais je pense que bitcoin n'est pas une bonne base (bitcoin est excellent mais je pense qu'il y a mieux).
Bitcoin simplifier : il y a plein de chose dans les dernières version de Bitcoin qui ne nous seront pas utiles.
Ethereum : Smart contract
Monero : Annonyme (quoi que très compliquer dans sont système de tx)
Boinc : PoW économique en énergie
NXT : PoS, Plein de fonctionaliter anexe qui se base sur une blockchain, car avoir 50 blockchain pour 50 truc différent c'est chiant faut passer par un exchange pour changer les coins entre eux, alors que si le coin ne se contente pas juste d'être un coin sa simplifie bcp les choses.

**Comment by Slals** [comment]
L'objectif n'est pas de faire un système fourre-tout. Il n'y a aucune nécessité à faire ce que d'autres font déjà, par exemple les contrats intelligents.

Le fait de reposer sur Bitcoin est un choix favorisant la simplicité du protocole. En réalité peu de choses seront "comme" Bitcoin puisque le système implique des éléments fondamentalement nouveaux. Disons que Bitcoin est pris comme repère pour certains points comme la structure des blocs.

Je réfléchis encore sur la manière dont les choses seront intégrées, j'envisage, éventuellement d'intégrer une système de sidechains pour déployer de nouveaux algorithmes de consensus.
