### ISSUE TITLE
Problème dans le lexique

### ISSUE THREAD

**Issue by Jorropo** [Chaine-de-Blocs/educoin#6]
La diférenciation entre protocole et cryptomonais est selon moi mauvaise, (enfaite elle est vrai)
Le problème est avec protocole, qui à 2 définition qui nous concerne :
- L'actuel, le code qui permet à la cryptomonai de fonctionner
- Mais aussi, comment les nodes comunique entre eux.

Je propose de renomer la première définition : **implémentation**, bien que sa sois faut car une implémentation est un code éxécutable d'un procotole, là où un protocole est juste théorique ou présent dans une doc.

Cella serait bien plus pratique car on pourait différencier comment les nodes communiquent de comment elles fonctionent.

Quelle est votre avis ?

**Comment by Slals** [comment]
Tu pourrais renvoyer vers les endroits où tu estimes que ça pose problème ?

Pour _Protocole_ je prends la définition de [Wikipedia](https://fr.wikipedia.org/wiki/Protocole) :
`On nomme protocole les conventions qui facilitent une communication sans faire directement partie du sujet de la communication elle-même.`

Le protocole est ce qui régie la manière dont les acteurs de Rhizome communiqueront.

La cryptomonnaie quant à elle est effectivement le sujet relatif au fonctionnement du protocole. C'est un "objet" purement identifiable puisant sa source d'un ensemble de règles appliquées, venant du fonctionnement du protocole donc.

Tes 2 définitions sont la face d'une même pièce. Le code est ce qui dicte aux acteurs comment communiquer. Ce que j'appelle "cryptomonnaie" dans ce cas particulier est l'objet produit par le fonctionnement du protocole.

Un protocole _A_ produira une cryptomonnaie _a_, un protocole _B_ produira une cryptomonnaie _b_. En somme, les deux termes désignent deux choses relatives mais la nature de la chose est complètement différente.
