### ISSUE TITLE
Quel algo ? (Proposition)

### ISSUE THREAD

**Issue by Jorropo** [Chaine-de-Blocs/educoin#7]
Je n'est pas vus dans la documentation quelle algo est utiliser par le protocol pour le pow.
Je voudrais donc savoir qu'elle sera l'algo(s) ?

Mais sinon je propose sa :
Je propose de faire du multi algo / multi diff cela est la seul condition pour que les gpus et asics sois sur un pied d'égaliter,
Cela rend très difficile une attaque de type 51%
Ce que je propose :

Algos :
- SHA256d (pour les asics)
- Scrypt (pour les asics)
- Dagger Hashimoto (pour les gpus amd)
- Equihash (pour les gpus nvidia)

Difficulté :
Chaque algo aurat comme target de difficulté (block time * 4) (vue qu'il y a 4 algo faut que chaque algo produisent 1 block 4 fois moins souvent que la target)
Mais sinon on peut aussi faire 4 algo mais 2 difficulté, une pour les asics (sha256d, scrypt) et une pour les gpus (Dagger Hashimoto, Equihash)

Cela n'est pas si compliquer, je pourait le faire.

**Comment by dxokal** [comment]
J'adhère à cette idée de @Jorropo. @Slaals qu'en pense-tu ?

**Comment by Slals** [comment]
Pour l'instant c'est indécis. On peut en discuter ici.

Je pensais partir sur [Algorand](https://www.algorand.com/).

La première raison est que ce projet me semble pertinent. Il est basé sur une algorithme de consensus rendant théoriquement improbable le fork (je parle de [reorg](https://en.bitcoin.it/wiki/Chain_Reorganization)), le fork, compte tenu de la particularité de Rhizome pourrait être un challenge et compliquer les choses. L'absence de fork est donc du pain bénie.

Initialement j'envisageais de faire une preuve de travail, pour des raisons simples :
- Relativement simple à implanter,
- Sécurisé,
- Ca a fait ses preuves,
- Ca injecte de la valeur intrinsèque aux jetons.

Après réflexion, j'ai une idée de comment la valeur intrinsèque pourrait être amenée indépendamment de l'algorithme de consensus. J'en parlerais plus en détail lorsque je reprendrais le projet en main.

La discussion est ouverte ceci dit !
